package com.myspace.restcall;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LeaseModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer annualRent;
	private java.lang.Boolean isAutoApproved;

	public LeaseModel() {
	}

	public java.lang.Integer getAnnualRent() {
		return this.annualRent;
	}

	public void setAnnualRent(java.lang.Integer annualRent) {
		this.annualRent = annualRent;
	}

	public java.lang.Boolean getIsAutoApproved() {
		return this.isAutoApproved;
	}

	public void setIsAutoApproved(java.lang.Boolean isAutoApproved) {
		this.isAutoApproved = isAutoApproved;
	}

	public LeaseModel(java.lang.Integer annualRent,
			java.lang.Boolean isAutoApproved) {
		this.annualRent = annualRent;
		this.isAutoApproved = isAutoApproved;
	}

}